# Generated by Django 5.2 on 2025-05-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_add_initial_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(auto_created=True, max_length=50, unique=True, verbose_name='رمز المنتج'),
        ),
    ]
