# Generated by Django 5.2 on 2025-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(auto_created=True, blank=True, max_length=50, verbose_name='رمز المنتج'),
        ),
    ]
