# Generated by Django 5.2 on 2025-04-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_initial'),
        ('user_accounts', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user_accounts.customer', verbose_name='المتجر'),
        ),
    ]
