# Generated by Django 5.2 on 2025-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_city',
            field=models.CharField(default=3, max_length=100, verbose_name='مدينة المتجر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store_location',
            field=models.CharField(default=(24.697292, 46.669839), max_length=255, verbose_name='موقع المتجر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(default='abc', max_length=100, verbose_name='اسم المتجر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store_phone',
            field=models.CharField(default=123, max_length=20, verbose_name='هاتف المتجر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('accepted', 'تم قبول الطلب'), ('processing', 'قيد التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
