# Generated by Django 5.2 on 2025-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_set_store_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_location',
            field=models.CharField(max_length=100, verbose_name='موقع المتجر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_name',
            field=models.CharField(max_length=255, verbose_name='اسم المتجر'),
        ),
    ]
