# Generated by Django 5.2 on 2025-04-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_companyprofile_bio_alter_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'متجر', 'verbose_name_plural': 'العملاء'},
        ),
    ]
