# Generated by Django 5.2 on 2025-04-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_companyprofile_company_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_category',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='category',
            field=models.CharField(default='غذائية', max_length=50, verbose_name='صنف الشركة'),
        ),
    ]
