# Generated by Django 5.2 on 2025-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_remove_companyprofile_company_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='store_name',
            field=models.CharField(max_length=100, verbose_name='اسم المتجر'),
        ),
    ]
