# Generated by Django 5.2 on 2025-04-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_alter_customerprofile_store_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'متجر', 'verbose_name_plural': 'المتاجر'},
        ),
    ]
