# Generated by Django 5.2 on 2025-04-28 06:30

from django.db import migrations, models
import django.db.models.deletion

def migrate_categories(apps, schema_editor):
    CompanyProfile = apps.get_model('user_accounts', 'CompanyProfile')
    ProductCategory = apps.get_model('product_catalog', 'ProductCategory')
    
    # Get or create the default category
    default_category, created = ProductCategory.objects.get_or_create(
        name="غذائية",
        defaults={'description': "المنتجات الغذائية"}
    )
    
    # Update all company profiles to use the default category
    for profile in CompanyProfile.objects.all():
        profile.new_category = default_category
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_add_initial_category'),
        ('user_accounts', '0007_alter_customer_options'),
    ]

    operations = [
        # 1. Add new field
        migrations.AddField(
            model_name='companyprofile',
            name='new_category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='product_catalog.productcategory',
                verbose_name='صنف الشركة'
            ),
        ),
        # 2. Copy data
        migrations.RunPython(migrate_categories),
        # 3. Remove old field
        migrations.RemoveField(
            model_name='companyprofile',
            name='category',
        ),
        # 4. Rename new field
        migrations.RenameField(
            model_name='companyprofile',
            old_name='new_category',
            new_name='category',
        ),
    ]
