# Generated by Django 5.2 on 2025-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_alter_companyprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='baner',
            field=models.ImageField(blank=True, upload_to='company_baners/', verbose_name='Baner'),
        ),
    ]
