# Generated by Django 5.2 on 2025-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='baner',
            field=models.ImageField(upload_to='company_baners/', verbose_name='Baner'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
